spring:
  mail:
    host: smtp.qq.com
    username: 1424332438@qq.com
    password: osrwprttuiafidag
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: ture